mysite/myauth/urls.py
# from django.contrib.auth.views import LoginView
from django.urls import path
from .views import (
    MyLoginView,
    MyLogoutView,
    AboutMeView,
    RegisterView,
    # login_view,
    # logout_view,
    get_cookie_view,
    set_cookie_view,
    get_session_view,
    set_session_view,
    FooBarView,
    UsersListView,
    UsersDetailView,
    UpdateProfileView,
    HelloView,
)

app_name = 'myauth'

urlpatterns = [
    # path('login/', login_view, name='login'),
    # path(
    #     'login/',
    #     LoginView.as_view(
    #         template_name='myauth/login.html',
    #         redirect_authenticated_user=True,
    #     ),
    #     name='login'
    # ),
    path('hello/', HelloView.as_view(), name='hello'),

    path('login/', MyLoginView.as_view(), name='login'),
    path('logout/', MyLogoutView.as_view(), name='logout'),
    path('about-me/', AboutMeView.as_view(), name='about-me'),
    path('register/', RegisterView.as_view(), name='register'),

    path('cookie/get/', get_cookie_view, name='cookie-get'),
    path('cookie/set/', set_cookie_view, name='cookie-set'),

    path('session/get/', get_session_view, name='session-get'),
    path('session/set/', set_session_view, name='session-set'),

    path('foo-bar/', FooBarView.as_view(), name='foo-bar'),

    path('users/', UsersListView.as_view(), name='user-list'),
    path('users/<int:pk>/', UsersDetailView.as_view(), name='user-detail'),
    path('users/<int:pk>/update/', UpdateProfileView.as_view(), name='update-profile'),
]

mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns

from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView

urlpatterns = [
    path('req/', include('requestdataapp.urls')),

]

urlpatterns += i18n_patterns(
    path('admin/docs/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('myauth.urls')),
    path('shop/', include('shopapp.urls')),
    path('api/', include('myapiapp.urls')),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger'),
    path('api/schema/redoc', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
)

if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )

mysite/shopapp/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from .views import (
    ShopIndexView,
    GroupsListView,
    ProductsListView,
    ProductCreateView,
    ProductsDataExportView,
    ProductDetailsView,
    ProductUpdateView,
    ProductDeleteView,
    OrdersListView,
    OrdersDetailView,
    OrderCreateView,
    OrderUpdateView,
    OrderDeleteView,
    OrdersDataExportView,
    ProductViewSet,
    OrderViewSet,
)

app_name = 'shopapp'

routers = DefaultRouter()
routers.register('products', ProductViewSet)
routers.register('orders', OrderViewSet)


urlpatterns = [
    path('api/', include(routers.urls), name='api'),

    path('', ShopIndexView.as_view(), name='index'),

    path('groups/', GroupsListView.as_view(), name='groups_list'),

    path('products/', ProductsListView.as_view(), name='products_list'),
    path('products/create/', ProductCreateView.as_view(), name='product_create'),
    path('products/export/', ProductsDataExportView.as_view(), name='products-export'),
    path("products/<int:pk>/", ProductDetailsView.as_view(), name='product_details'),
    path('products/<int:pk>/update/', ProductUpdateView.as_view(), name='product_update'),
    path('products/<int:pk>/archive/', ProductDeleteView.as_view(), name='product_delete'),

    path('orders/', OrdersListView.as_view(), name='orders_list'),
    path('orders/create/', OrderCreateView.as_view(), name='order_create'),
    path('orders/export/', OrdersDataExportView.as_view(), name='orders-export'),
    path('orders/<int:pk>/', OrdersDetailView.as_view(), name='order_details'),
    path('orders/<int:pk>/update/', OrderUpdateView.as_view(), name='order_update'),
    path('orders/<int:pk>/delete/', OrderDeleteView.as_view(), name='order_delete'),
]

mysite/shopapp/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import gettext_lazy as _


def product_preview_directory_path(instance: 'Product', filename: str) -> str:
    return 'products/product_{pk}/preview/{filename}'.format(
        pk=instance.pk,
        filename=filename
    )


class Product(models.Model):
    """
    Модель Product представляет товар,
    который можно продавать в интернет-магазине.

    Заказы тут: :model:`shopapp.Order`
    """
    class Meta:
        ordering = ['name', 'price']
        verbose_name = _('Product')
        verbose_name_plural = _('Products')

    name = models.CharField(max_length=100)
    description = models.TextField(null=False, blank=True)
    price = models.DecimalField(default=0, max_digits=8, decimal_places=2)
    discount = models.SmallIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    archived = models.BooleanField(default=False)
    preview = models.ImageField(null=True, blank=True, upload_to=product_preview_directory_path)

    # @property
    # def description_short(self) -> str:
    #     if len(self.description) < 48:
    #         return self.description
    #     return self.description[:48] + '...'

    def __str__(self) -> str:
        return f'Product (pk={self.pk}, name={self.name!r})'


def product_images_directory_path(instance: 'ProductImage', filename: str) -> str:
    return 'products/product_{pk}/preview/{filename}'.format(
        pk=instance.pk,
        filename=filename,
    )


class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='images')
    image = models.ImageField(upload_to=product_images_directory_path)
    description = models.CharField(max_length=200, null=True, blank=True)


class Order(models.Model):
    class Meta:
        verbose_name = _('Order')
        verbose_name_plural = _('Orders')

    delivery_address = models.TextField(null=True, blank=True)
    promocode = models.CharField(max_length=20, null=False, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    # one-to-many
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    # many-to-many
    products = models.ManyToManyField(Product, related_name='orders')

    receipt = models.FileField(null=True, upload_to='orders/receipts/')

    def __str__(self) -> str:
        return f'Order (pk={self.pk})'

mysite/shopapp/views.py
"""
В этом модуле лежат различные наборы представлений.

View интернет-магазина: по товарам, заказам и т.д.
"""

from timeit import default_timer

from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import Group
from django.http import HttpResponse, HttpRequest, HttpResponseRedirect, JsonResponse
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from docutils.nodes import description
from rest_framework.viewsets import ModelViewSet
from rest_framework.filters import SearchFilter, OrderingFilter
from django_filters.rest_framework import DjangoFilterBackend

from .models import Product, Order, ProductImage
from .forms import ProductForm, OrderForm, GroupForm
from .serializers import ProductSerializer, OrderSerializer
from drf_spectacular.utils import extend_schema, OpenApiResponse


@extend_schema(description='Product views CRUD')
class ProductViewSet(ModelViewSet):
    """
    Набор представлений для действий над Product
    Полный CRUD для сущностей товара
    """
    queryset = Product.objects.all()
    serializer_class = ProductSerializer
    filter_backends = [
        SearchFilter,
        DjangoFilterBackend,
        OrderingFilter,
    ]
    search_fields = [
        'name',
        'description',
    ]
    ordering_fields = [
        'name',
        'price',
        'discount',
    ]

    filterset_fields = [
        'name',
        'description',
        'price',
        'discount',
        'archived',
    ]

    @extend_schema(
        summary='Get one product by ID',
        description='Retrieves **product**, returns 404 if not found',
        responses={
            200: ProductSerializer,
            400: OpenApiResponse(description='Empty response, product by id not found'),
        }
    )
    def retrieve(self, *args, **kwargs):
        return super().retrieve(*args, **kwargs)


class OrderViewSet(ModelViewSet):
    queryset = Order.objects.all()
    serializer_class = OrderSerializer
    filter_backends = [
        SearchFilter,
        DjangoFilterBackend,
        OrderingFilter,
    ]
    search_fields = [
        'delivery_address',
        'promocode',
        'created_at',
    ]
    ordering_fields = [
        'delivery_address',
        'promocode',
        'created_at',
        'user',
        'products',
    ]

    filterset_fields = [
        'delivery_address',
        'promocode',
        'created_at',
        'user',
        'products',
    ]


class ShopIndexView(View):
    def get(self, request: HttpRequest) -> HttpResponse:
        products = [
            ('Laptop', 1999),
            ('Desktop', 2999),
            ('Smartphone', 999),
        ]
        context = {
            'time_running': default_timer(),
            'products': products,
            'items': 5,
        }
        return render(request, 'shopapp/shop-index.html', context=context)


class GroupsListView(View):
    def get(self, request: HttpRequest) -> HttpResponse:
        context = {
            'form': GroupForm(),
            'groups': Group.objects.prefetch_related('permissions').all(),
        }
        return render(request, 'shopapp/groups-list.html', context=context)

    def post(self, request: HttpRequest) -> HttpResponse:
        form = GroupForm(request.POST)
        if form.is_valid():
            form.save()
        # return redirect(reverse('shopapp:groups_list'))
        return redirect(request.path)


class ProductDetailsView(DetailView):
    template_name = 'shopapp/product-details.html'
    # model = Product
    context_object_name = 'product'
    queryset = Product.objects.prefetch_related('images')
    # Product.objects.filter(archived=False),

    # def get(self, request: HttpRequest, pk: int) -> HttpResponse:
    #     # product = Product.objects.get(pk=pk)
    #     product = get_object_or_404(Product, pk=pk)
    #     context = {
    #         'product': product,
    #     }
    #     return render(request, 'shopapp/product-details.html', context=context)


class ProductsListView(ListView):
    template_name = 'shopapp/products-list.html'
    # model = Product
    context_object_name = 'products'
    queryset = (
        Product.objects.filter(archived=False)
    )

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context['products'] = Product.objects.all()
    #     return context


class ProductCreateView(PermissionRequiredMixin, CreateView):
    permission_required = 'shopapp.add_product'

    # def test_func(self):
    #     return self.request.user.is_superuser
    model = Product
    form_class = ProductForm  # аналогично: fields = 'name', 'price', 'description', 'discount'
    success_url = reverse_lazy('shopapp:products_list')

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)

    # В задании просят прописывать методы гет и пост, но зачем, если в классе CreateView все происходит под капотом.
    # def get(self, request: HttpRequest) -> HttpResponse:
    #     form = ProductForm()
    #     context = {
    #         'form': form,
    #     }
    #     return render(request, 'shopapp/product_form.html', context=context)
    #
    # def post(self, request: HttpRequest) -> HttpResponse:
    #     form = ProductForm(request.POST)
    #     if form.is_valid():
    #         form.save()
    #         # url = reverse('shopapp:products_list')
    #     return redirect(request.path)


class ProductUpdateView(UserPassesTestMixin, UpdateView):
    def test_func(self):
        product = self.get_object()
        user = self.request.user
        return self.request.user.is_superuser or (
                user.has_perm('shopapp.change_product') and product.created_by == user)

    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('shopapp:products_list')
    template_name_suffix = '_update_form'

    def get_success_url(self):
        return reverse(
            'shopapp:product_details',
            kwargs={'pk': self.object.pk}
        )

    def form_valid(self, form):
        response = super().form_valid(form)
        for image in form.files.getlist('images'):
            ProductImage.objects.create(
                product=self.object,
                image=image,
            )
        return response


class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy('shopapp:products_list')

    def form_valid(self, form):
        success_url = self.get_success_url()
        self.object.archived = True
        self.object.save()
        return HttpResponseRedirect(success_url)


class OrdersListView(LoginRequiredMixin, ListView):
    # template_name = 'shopapp/order_list.html'
    # model = Order
    # context_object = 'orders'
    queryset = (
        Order.objects.select_related('user').prefetch_related('products')
    )


class OrdersDetailView(PermissionRequiredMixin, DetailView):
    permission_required = 'shopapp.view_order'
    queryset = (
        Order.objects.select_related('user').prefetch_related('products')
    )


class OrderCreateView(CreateView):
    model = Order
    form_class = OrderForm
    success_url = reverse_lazy('shopapp:orders_list')


class OrderUpdateView(UpdateView):
    model = Order
    form_class = OrderForm
    success_url = reverse_lazy('shopapp:orders_list')
    template_name_suffix = '_update_form'

    def get_success_url(self):
        return reverse(
            'shopapp:order_details',
            kwargs={'pk': self.object.pk}
        )


class OrderDeleteView(DeleteView):
    model = Order
    success_url = reverse_lazy('shopapp:orders_list')


class ProductsDataExportView(View):
    def get(self, request: HttpRequest) -> JsonResponse:
        products = Product.objects.order_by('pk').all()
        products_data = [
            {
                'pk': product.pk,
                'name': product.name,
                'price': product.price,
                'archived': product.archived,
            }
            for product in products
        ]
        return JsonResponse({'products': products_data})


class OrdersDataExportView(UserPassesTestMixin, View):
    def test_func(self):
        return self.request.user.is_staff

    def get(self, request: HttpRequest) -> JsonResponse:
        orders = Order.objects.order_by('pk').all()
        orders_data = [
            {
                'pk': order.pk,
                'delivery_address': order.delivery_address,
                'promocode': order.promocode,
                'user_id': order.user_id,
                'products_id': [product.id for product in order.products.all()]
            }
            for order in orders
        ]
        return JsonResponse({"orders": orders_data})

# def create_order(request: HttpRequest) -> HttpResponse:
#     if request.method == 'POST':
#         form = OrderForm(request.POST)
#         if form.is_valid():
#             form.save()
#             url = reverse('shopapp:orders_list')
#             return redirect(url)
#     else:
#         form = OrderForm()
#     context = {
#         'form': form,
#     }
#     return render(request, 'shopapp/order_form.html', context=context)


# def create_product(request: HttpRequest) -> HttpResponse:
#     if request.method == 'POST':
#         form = ProductForm(request.POST)
#         if form.is_valid():

mysite/shopapp/templates/shopapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            Base Title
        {% endblock %}
    </title>
</head>
<body>
{% block main %}
    Base main
{% endblock %}

<div>
    {% now 'H:i' %}
</div>

<div>
    {% now 'l' as current_weekday %}
    Today is
    {{ current_weekday }}
</div>
</body>
</html>

mysite/shopapp/templates/shopapp/create-order.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Create Order
{% endblock %}

{% block main %}

    <h1>Create a new order</h1>

    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">
                Create
            </button>
        </form>
    </div>

    <div>
        <a href="{% url 'shopapp:orders_list' %}">
            Back to orders list
        </a>
    </div>

{% endblock %}

mysite/shopapp/templates/shopapp/create-product.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Create Product
{% endblock %}

{% block main %}
    <h1>Create a new product</h1>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">
                Create
            </button>
        </form>
    </div>

    <div>
        <a href="{% url 'shopapp:products_list' %}">
            Back to products list
        </a>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/groups-list.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Groups List
{% endblock %}

{% block main %}
    <h1>Groups:</h1>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Create</button>
        </form>
    </div>
    <div>
    {% if not groups %}
        <h3>No groups yet</h3>
    {% else %}
    <ul>
        {% for group in groups %}
            <li>
                <div>{{ group.name }}</div>
                <ul>
                    {% for permission in group.permissions.all %}
                        <li>{{ permission.name }} (<code>{{ permission.codename }}</code>)</li>
                    {% endfor %}

                </ul>
            </li>
        {% endfor %}
    </ul>
    {% endif %}


{#    {{ groups }}#}
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/order_confirm_delete.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Confirm delete {{ object.name }}
{% endblock %}

{% block main %}
    <h1>Are you sure you want to delete {{ object.name }}?</h1>
    <br>
    <div><a href="{% url 'shopapp:order_details' pk=object.pk %}">Back to order</a></div>
    <br>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Delete</button>
        </form>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/order_detail.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Order #{{ object.pk }} details
{% endblock %}

{% block main %}
    <h1>Order #{{ object.pk }}</h1>
    <div>
        <p>Order by {% firstof object.user.first_name object.user.username %}</p>
        <p>Promocode: <code>{{ object.promocode }}</code></p>
        <p>Delivery address: {{ object.delivery_address }}</p>
        <div>
            Products in Order:
            <ul>
                {% for product in object.products.all %}
                    <li>{{ product.name }}: ${{ product.price }}</li>
                {% endfor %}

            </ul>
        </div>
    </div>

    <div><a href="{% url 'shopapp:order_update' pk=object.pk %}">Update order</a></div>
    <div><a href="{% url 'shopapp:order_delete' pk=object.pk %}">Delete order</a></div>
    <div><a href="{% url 'shopapp:orders_list' %}">Back to orders</a></div>
{% endblock %}

mysite/shopapp/templates/shopapp/order_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Create Order
{% endblock %}

{% block main %}

    <h1>Create a new order</h1>

    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">
                Create
            </button>
        </form>
    </div>

    <div>
        <a href="{% url 'shopapp:orders_list' %}">
            Back to orders list
        </a>
    </div>

{% endblock %}

mysite/shopapp/templates/shopapp/order_list.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Orders List
{% endblock %}

{% block main %}
    <h1>Orders:</h1>
    {% if object_list %}
        <div>
            {% for order in object_list %}
                <div>
                    {#                    <p>{{ order.user.username }}</p>#}
                    <p><a href="{% url 'shopapp:order_details' pk=order.pk %}">Details #{{ order.pk }}</a></p>
                    <p>Order by {% firstof order.user.first_name order.user.username %}</p>
                    <p>Promocode: <code>{{ order.promocode }}</code></p>
                    <p>Delivery address: {{ order.delivery_address }}</p>
                    <div>
                        Products in Order:
                        <ul>
                            {% for product in order.products.all %}
                                <li>{{ product.name }}: ${{ product.price }}</li>
                            {% endfor %}

                        </ul>
                    </div>
                </div>
            {% endfor %}

        </div>
    {% else %}
        <h3>No orders yet</h3>
    {% endif %}
    
    <div>
        <a href="{% url 'shopapp:order_create' %}">
            Create a new order
        </a>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/order_update_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Update Order
{% endblock %}

{% block main %}
    <h1>Update a new order</h1>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Update</button>
        </form>
    </div>

    <div>
        <a href="{% url 'shopapp:order_details' pk=object.pk %}">Back to order #{{ object.pk }}</a>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/product-details.html
{% extends 'shopapp/base.html' %}

{% load i18n %}

{% block title %}
    {% translate 'Product' %} #{{ product.pk }}
{% endblock %}

{% block main %}
    <h1>{% translate 'Product' %} <strong>{{ product.name }}</strong></h1>
    <div>
        <div>{% translate 'Description' %}: <em>{{ product.description }}</em></div>
        <div>{% translate 'Price' %}: {{ product.price }}</div>
        <div>{% translate 'Discount' %}: {{ product.discount }}</div>
        <div>{% translate 'Archived' %}: {{ product.archived }}</div>
        {% translate 'None' as none %}
        <div>{% translate 'Created by' %}: {% firstof product.created_by none %}</div>

        {% if product.preview %}
            <img src="{{ product.preview.url }}" alt="{{ product.preview.name }}">
        {% endif %}

        <h3>{% translate 'Images' %}:</h3>
        {% if product.images %}
            <div>
                {% blocktranslate count images_count=product.images.count %}
                    There is only one image.
                    {% plural %}
                    There are {{ images_count }} images available.
                {% endblocktranslate %}
            </div>
            <div>
            {% for img in product.images.all %}
                <div>
                    <img src="{{ img.image.url }}" alt="{{ img.image.name }}">
                    <div>{{ img.description }}</div>
                </div>
            {% empty %}
                <div>{% translate 'No images yet' %}</div>
            {% endfor %}
        {% endif %}
        </div>

    </div>
    <div><a href="{% url 'shopapp:product_update' pk=product.pk %}">{% translate 'Update product' %}</a></div>
    <div><a href="{% url 'shopapp:product_delete' pk=product.pk %}">{% translate 'Archive product' %}</a></div>
    <div><a href="{% url 'shopapp:products_list' %}">{% translate 'Back to products list' %}</a></div>
{% endblock %}

mysite/shopapp/templates/shopapp/product_confirm_delete.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Confirm archive {{ object.name }}
{% endblock %}

{% block main %}
    <h1>Are you sure you want to archive {{ object.name }}?</h1>
    <br>
    <div><a href="{% url 'shopapp:product_details' pk=object.pk %}">Back to product</a></div>
    <br>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Archive</button>
        </form>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/product_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Create Product
{% endblock %}

{% block main %}
    <h1>Create a new product</h1>
    <div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Create</button>
        </form>
    </div>

    <div>
        <a href="{% url 'shopapp:products_list' %}">Back to products list</a>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/products-list.html
{% extends 'shopapp/base.html' %}

{% load i18n %}

{% block title %}
    {% translate 'Products List' %}
{% endblock %}

{% block main %}
    <h1>{% translate 'Products' %}:</h1>
    {% if products %}
        <div>
            {% blocktranslate count products_count=products|length %}
                There is only one product.
                {% plural %}
                There are {{ products_count }} products.
            {% endblocktranslate %}
        </div>
        <div>
            {% for product in products %}
                <div>
                    <p>
                        <a href="{% url 'shopapp:product_details' pk=product.pk %}">{% translate 'Name' context 'product name' %}: {{ product.name }}</a>
                    </p>
                    <p>{% translate 'Price' %}: {{ product.price }}</p>
                    {% translate 'no discount' as no_discount %}
                    <p>{% translate 'Discount' %}: {% firstof product.discount no_discount %}</p>
                    {% translate 'None' as none %}
                    <p>{% translate 'Created by' %}: {% firstof product.created_by none %}</p>

                    {% if product.preview %}
                        <img src="{{ product.preview.url }}" alt="{{ product.preview.name }}">
                    {% endif %}
                </div>

            {% endfor %}

        </div>
    {% else %}
        <h3>{% translate 'No products yet' %}</h3>
    {% endif %}
    <br>
    {% if perms.shopapp.add_product %}
        <div>
            <a href="{% url 'shopapp:product_create' %}">{% translate 'Create a new product' %}</a>
        </div>
    {% else %}
        {% url 'shopapp:product_create' as create_product_url %}
        {% blocktranslate %}
            <a href="{{ create_product_url }}">Create a new one</a>
        {% endblocktranslate %}
    {% endif %}
{% endblock %}

mysite/shopapp/templates/shopapp/shop-index.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Shop Index
{% endblock %}

{% block main %}
    <h1>
        Shop Main
    </h1>

    <div>
        Time running: {{ time_running }}
    </div>

    <div>
        {% lorem 3 p random %}
    </div>
    <div>
        <ul>
            {% for name, price in products %}
                <li>{{ name }} ({{ name|length }}): ${{ price }}</li>
                {% if name|length == 7 %}
                    <span>Lucky</span>
                {% endif %}
            {% empty %}
                No products here
            {% endfor %}

        </ul>
    </div>

    <div>
        <strong>
            You have {{ items }} cherr{{ items|pluralize:'y, ies' }}
        </strong>
    </div>
{% endblock %}