mysite/myauth/urls.py
# from django.contrib.auth.views import LoginView
from django.urls import path
from .views import (
    MyLoginView,
    MyLogoutView,
    AboutMeView,
    RegisterView,
    # login_view,
    # logout_view,
    get_cookie_view,
    set_cookie_view,
    get_session_view,
    set_session_view,
    FooBarView,
    UsersListView,
    UsersDetailView,
    UpdateProfileView,
    HelloView,
)

app_name = 'myauth'

urlpatterns = [
    # path('login/', login_view, name='login'),
    # path(
    #     'login/',
    #     LoginView.as_view(
    #         template_name='myauth/login.html',
    #         redirect_authenticated_user=True,
    #     ),
    #     name='login'
    # ),
    path('hello/', HelloView.as_view(), name='hello'),

    path('login/', MyLoginView.as_view(), name='login'),
    path('logout/', MyLogoutView.as_view(), name='logout'),
    path('about-me/', AboutMeView.as_view(), name='about-me'),
    path('register/', RegisterView.as_view(), name='register'),

    path('cookie/get/', get_cookie_view, name='cookie-get'),
    path('cookie/set/', set_cookie_view, name='cookie-set'),

    path('session/get/', get_session_view, name='session-get'),
    path('session/set/', set_session_view, name='session-set'),

    path('foo-bar/', FooBarView.as_view(), name='foo-bar'),

    path('users/', UsersListView.as_view(), name='user-list'),
    path('users/<int:pk>/', UsersDetailView.as_view(), name='user-detail'),
    path('users/<int:pk>/update/', UpdateProfileView.as_view(), name='update-profile'),
]

mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns

from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView

urlpatterns = [
    path('req/', include('requestdataapp.urls')),

]

urlpatterns += i18n_patterns(
    path('admin/docs/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('myauth.urls')),
    path('shop/', include('shopapp.urls')),
    path('api/', include('myapiapp.urls')),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger'),
    path('api/schema/redoc', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
)

if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )

mysite/myauth/models.py
from django.contrib.auth.models import User
from django.db import models


def user_preview_directory_path(instance: 'User', filename: str) -> str:
    return 'users/user_{pk}/avatar/{filename}'.format(pk=instance.pk, filename=filename)


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    agreement_accepted = models.BooleanField(default=False)
    avatar = models.ImageField(null=True, upload_to=user_preview_directory_path)

mysite/myauth/forms.py
from django import forms
from .models import Profile


class AvatarForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['avatar']


mysite/myauth/views.py
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required, permission_required, user_passes_test
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.views import LoginView, LogoutView
from django.http import HttpRequest, HttpResponse, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views.generic import TemplateView, CreateView, View, ListView, DetailView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.utils.translation import gettext_lazy as _, ngettext_lazy

from .forms import AvatarForm
from .models import Profile, User


class HelloView(View):
    welcome_message = _('welcome hello world')

    def get(self, request: HttpRequest) -> HttpResponse:
        items_str = request.GET.get('items') or 0
        items = int(items_str)
        products_line = ngettext_lazy(
            'one product',
            '{count} products',
            items,
        )
        products_line = products_line.format(count=items)
        return HttpResponse(
            f'<h1>{self.welcome_message}</h1>'
            f'\n<h2>{products_line}</h2>'
        )


class AboutMeView(LoginRequiredMixin, UpdateView):
    template_name = 'myauth/about-me.html'
    form_class = AvatarForm
    model = Profile
    success_url = reverse_lazy('myauth:about-me')
    context_object_name = 'profile'

    def get_object(self):
        profile, created = Profile.objects.get_or_create(user=self.request.user)
        return profile

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     profile = self.get_object()
    #     context['profile'] = profile
    #     return context

    def form_valid(self, form):
        profile = self.get_object()
        profile.avatar = form.cleaned_data['avatar']
        profile.save()
        return super().form_valid(form)


class UsersListView(LoginRequiredMixin, ListView):
    template_name = 'myauth/user_list.html'
    model = User
    context_object_name = 'users'


class UsersDetailView(LoginRequiredMixin, DetailView):
    template_name = 'myauth/user_detail.html'
    model = User
    context_object_name = 'user'

    def get_object(self, queryset=None):
        return get_object_or_404(User, pk=self.kwargs['pk'])

    def get_success_url(self):
        return reverse('user-details', kwargs={'pk': self.kwargs['pk']})


class UpdateProfileView(UserPassesTestMixin, UpdateView):
    template_name = 'myauth/update_profile.html'
    model = Profile
    form_class = AvatarForm
    success_url = reverse_lazy('myauth:about-me')

    # def get_success_url(self):
    #     return reverse('myauth:user-detail', kwargs={'pk': self.object.pk})

    def test_func(self):
        user = self.request.user
        return self.request.user.is_staff or user == self.request.user

    def get_object(self, queryset=None):
        user = get_object_or_404(User, pk=self.kwargs['pk'])
        profile, _ = Profile.objects.get_or_create(user=user)
        return profile
    # def form_valid(self, form):
    #     profile = self.request.user
    #     profile.avatar = form.cleaned_data['avatar']
    #     profile.save()
    #     return super().form_valid(form)


class RegisterView(CreateView):
    form_class = UserCreationForm
    template_name = 'myauth/register.html'
    success_url = reverse_lazy('myauth:about-me')

    def form_valid(self, form):
        response = super().form_valid(form)
        Profile.objects.create(self.object)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password1']
        user = authenticate(self.request, username=username, password=password)
        login(request=self.request, user=user)
        return response


class MyLoginView(LoginView):
    template_name = 'myauth/login.html'
    redirect_authenticated_user = True


class MyLogoutView(LogoutView):
    next_page = reverse_lazy('myauth:login')


def logout_view(request: HttpRequest) -> HttpResponse:
    logout(request)
    return redirect(reverse('myauth:login'))


def login_view(request: HttpRequest) -> HttpResponse:
    if request.method == 'GET':
        if request.user.is_authenticated:
            return redirect('/admin/')

        return render(request, 'myauth/login.html')

    username = request.POST.get('username')
    password = request.POST.get('password')

    user = authenticate(request, username=username, password=password)
    if user:
        login(request, user)
        return redirect('/admin/')
    return render(request, 'myauth/login.html', {'error': 'Invalid username or password'})


@user_passes_test(lambda u: u.is_superuser)
def set_cookie_view(request: HttpRequest) -> HttpResponse:
    response = HttpResponse('Cookie set')
    response.set_cookie('fizz', 'buzz', max_age=3600)
    return response


# @login_required
def get_cookie_view(request: HttpRequest) -> HttpResponse:
    value = request.COOKIES.get('fizz', 'default_value')
    return HttpResponse(f'Cookie value: {value!r}')


@permission_required('myauth.view_profile', raise_exception=True)
def set_session_view(request: HttpRequest) -> HttpResponse:
    request.session['foobar'] = 'spameggs'
    return HttpResponse('Session set!')


@login_required
def get_session_view(request: HttpRequest) -> HttpResponse:
    value = request.session.get('foobar', 'default_value')
    return HttpResponse(f'Session value: {value!r}')


class FooBarView(View):
    def get(self, request: HttpRequest) -> JsonResponse:
        return JsonResponse({'foo': 'bar', 'spam': "eggs"})

mysite/myauth/templates/myauth/about-me.html
{% extends 'myauth/base.html' %}

{% block title %}
    About me
{% endblock %}

{% block main %}
    <h1>User info</h1>
    {% if user.is_authenticated %}
        <h2>Details</h2>
        <p>Username: {{ user.username }}</p>
        <p>First name: {{ user.first_name }}</p>
        <p>Last name: {{ user.last_name }}</p>
        <p>Email: {{ user.email }}</p>
        <p>Bio: {{ user.profile.bio }}</p>

        {% if profile.avatar %}
            <img src="{{ profile.avatar.url }}" alt="{{ profile.avatar.name }}">
        {% else %}
            <p>No avatar yet</p>
        {% endif %}
        <div><a href="{% url 'myauth:user-list' %}">Back to users list</a></div>

        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">
                Update Avatar
            </button>
        </form>
    {% else %}
        <h2>User is anonymous</h2>
    {% endif %}
{% endblock %}

mysite/myauth/templates/myauth/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}

    {% endblock %}</title>
</head>
<body>
{% block main %}

{% endblock %}
</body>
</html>

mysite/myauth/templates/myauth/login.html
{% extends 'myauth/base.html' %}

{% block title %}
    Login
{% endblock %}

{% block main %}
    <form method="post">
        {% csrf_token %}

        {{ form.as_p }}

        <button type="submit">Login</button>
    </form>
{% endblock %}

mysite/myauth/templates/myauth/login_old.html
{% extends 'myauth/base.html' %}

{% block title %}
    Login
{% endblock %}

{% block main %}
    <form method="post">
        {% csrf_token %}
        {% if error %}
            <p style="color: red">{{ error }}</p>
        {% endif %}

        <p>
            <label for="username">Username:</label>
            <input type="text" id="username" name="username" required>
        </p>
        <p>
            <label for="password">Password:</label>
            <input type="text" id="password" name="password" required>
        </p>
        <button type="submit">Login</button>
    </form>
{% endblock %}

mysite/myauth/templates/myauth/register.html
{% extends 'myauth/base.html' %}

{% block title %}
    Registration
{% endblock %}

{% block main %}
    <h1>Register</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Register">
    </form>
{% endblock %}

mysite/myauth/templates/myauth/update_profile.html
{% extends 'myauth/base.html' %}
{% block title %}
    Update Profile
{% endblock %}
{% block main %}
    <h1>Update Profile</h1>
    <div><a href="{% url 'myauth:user-list' %}">Back to users list</a></div>

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Update</button>
    </form>
{% endblock %}

mysite/myauth/templates/myauth/user_detail.html
{% extends 'myauth/base.html' %}
{% block title %}
    User Details
{% endblock %}

{% block main %}
    <h1>User {{ user.username }} Details</h1>
    <a href="{% url 'myauth:user-list' %}">Back to list</a>
    <br>
    {% if request.user == user or request.user.is_staff %}
        <a href="{% url 'myauth:update-profile' user.pk %}">Update Profile</a>
    {% endif %}
    <h2>Name: {{ user.username }}</h2>
    <div>Bio: {{ user.profile.bio }}</div>
    <div>Agreement accepted: {{ user.profile.agreement_accepted }}</div>

    {% if user.profile.avatar %}
        <img src="{{ user.profile.avatar.url }}" alt="Avatar">
    {% else %}
        <p>No avatar available.</p>
    {% endif %}

{% endblock %}

mysite/myauth/templates/myauth/user_list.html
{% extends 'myauth/base.html' %}

{% block title %}
    User List
{% endblock %}

{% block main %}
    <h1>User List</h1>
    <div><a href="{% url 'myauth:about-me' %}">About me</a></div>
    <div><a href="{% url 'myauth:logout' %}">Logout</a></div>
    <h3>Details:</h3>
    <ul>
        {% for user in users %}
            <li><a href="{% url 'myauth:user-detail' user.pk %}">{{ user.username }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}